### ISSUE TITLE
Set up google cloud platform project

### ISSUE THREAD

**Issue by seandavi** [nih-cfde/icc-eval-core#21]
@vincerubinetti do you have a google cloud project set up for cfde? If not, I can get one set up. We will likely need one for the google analytics stuff (see #14 ) and it may be helpful for other small compute or database tasks.

**Comment by vincerubinetti** [comment]
I have one set up and have a preliminary ingest working. However, I set this up through my personal Gmail, and we may want to do it with a department account. Or perhaps we can keep the one I've created and just add other owner-level users to it.

**Comment by vincerubinetti** [comment]
I think we don't actually have an account for GCP projects that is central to the department or SET. But, since I've invited Sean, Casey, and Faisal as owners of the project I've set up, it at least passes the "bus test".
