### ISSUE TITLE
Consider GitHub Traffic Metrics

### ISSUE THREAD

**Issue by cgreene** [nih-cfde/icc-eval-core#9]
This will require that we get a token from each team with relevant permissions for the appropriate repositories. Consider if the benefit is greater than the time cost across teams:
https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#about-repository-traffic

**Comment by vincerubinetti** [comment]
Someone had mentioned https://github.com/AGWA/git-crypt for this type of thing. I'm slightly worried that doing this (or any similar solution), we'll accidentally commit the master password for the encrypted file and leak everyone's keys.

I almost feel that we should just collect and add teams' keys one by one as individual github repository secrets, e.g. `GITHUB_API_KEY_ R03OD032630`. If needed for easier local testing, we could store them permanently in DBMI SET's 1password vault as a `.env` file, which we'll add to `.gitignore`.

Further, if we keep the keys unencrypted, [GitHub's secret scanning feature](https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/push-protection-for-repositories-and-organizations#enabling-secret-scanning-as-a-push-protection-for-an-organization) (which I've already enabled in this repo) should be able to catch accidentally pushed keys, whereas it wouldn't be able to catch a master git-crypt password or encrypted secrets.

**Comment by seandavi** [comment]
I'd envision this as starting with just the nih-cfde organization which we have access to. It's a mix of repos (https://github.com/orgs/nih-cfde/repositories), but the entire org is accessible to us. 

For access tokens/keys, I'd stick to environment variables and not use files. Inject the tokens as environment variables into the workflow using github secrets. Here is an example: https://github.com/seandavi/omicidx-gh-etl/blob/main/.github/workflows/ncbi_sra_etl.yaml

We could also look into creating a "github app" that could be granted access directly. I haven't done one of these, but worth a look at some point.

**Comment by vincerubinetti** [comment]
Since all of these endpoints are limited to the past 14 days, we'd have to really stay on top of running the pipeline regularly to not have gaps in this data. As discussed above, this would also require fairly significant work to gather, store, and update (after expiration) github tokens.

As such, we might want to consider forgoing this feature. The other public metrics that we are already ingesting (watchers, stars, forks, commits, contributors, etc) may be good enough for demonstrating usage stats.

**Comment by cgreene** [comment]
I used "consider" in the title to make this pretty soft as I was concerned about those issues. To me, this feels pretty low priority given what we're already measuring and given the technical changes, I'm fine with closing the issue.
